source 'https://rubygems.org'
gem 'coffee-rails', '~> 4.0.0'

gem 'jbuilder', '~> 2.0'

gem 'jquery-rails'

gem 'minitest-rails'

gem 'rails', '4.1.0'

gem 'rake'

gem 'sass-rails', '~> 4.0.3'

gem 'sqlite3'

gem 'turbolinks'

gem 'uglifier', '>= 1.3.0'



gem 'sdoc', '~> 0.4.0',          group: :doc


gem 'spring',        group: :development

group :test do
  gem "minitest-rails-capybara"

end
